quarkus.http.port=8081

quarkus.datasource.db-kind = postgresql 

%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.datasource.username=tanalista
%dev.quarkus.datasource.password=tanalista_pass
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tanalista
quarkus.flyway.migrate-at-start=true

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:tanalista;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
%test.quarkus.flyway.migrate-at-start=false
